export default {
    products: [
        {
            _id: '123',
            name: 'slim Shirt',
            category: 'shirts',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '2',
            name: 'Fit Shirt',
            category: 'shirts',
            image: '/images/d1.jpg',
            price: 50,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '3',
            name: 'Best Pants',
            image: '/images/d1.jpg',
            category: 'pants',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
        },
        {
            _id: '4',
            name: 'Best Pants',
            image: '/images/d1.jpg',
            category: 'pants',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
        },
    ],
};
